title: Minimum Required Tasks for Copilot Adoption
description: A step-by-step guide for rolling out GitHub Copilot at scale
theme: jekyll-theme-cayman
baseurl: "/copilot-adoption"
url: "https://samqbush.github.io"
repository: samquakenbush/copilot-adoption

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gfm-admonitions
  - jekyll-toc

# GitHub Pages settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-