title: Minimum Required Tasks for Copilot Adoption
description: A step-by-step guide for rolling out GitHub Copilot at scale
theme: jekyll-theme-cayman
baseurl: "/copilot-adoption"
url: "https://samqbush.github.io"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages settings
markdown: kramdown
permalink: pretty